# Generated by Django 3.0.3 on 2020-07-25 02:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marca',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('birthdate', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(default=0, verbose_name='Tarifa')),
                ('duration_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Duración KM')),
                ('days', models.IntegerField(default=0, verbose_name='Días')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Año')),
                ('plaque', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('km_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Km Actual')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client', verbose_name='Cliente')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Exemplar', verbose_name='Modelo/Marca')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('km_service', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.IntegerField(default=0)),
                ('dscto', models.IntegerField(default=0)),
                ('iva', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('type_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Service')),
                ('veh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Vehicle')),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.Inventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Sale')),
            ],
            options={
                'verbose_name': 'Det. Venta',
                'verbose_name_plural': 'Det. Ventas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Contracts')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Sale')),
            ],
            options={
                'verbose_name': 'Det. Empleado',
                'verbose_name_plural': 'Det. Empleados',
                'ordering': ['-id'],
            },
        ),
    ]
