# Generated by Django 3.0.3 on 2020-07-25 02:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de finalización')),
                ('rmu', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puesto de Trabajos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('week', models.IntegerField(default=0)),
                ('days_work', models.IntegerField(default=0)),
                ('dsctos', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Contracts')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Teléfono Celular')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('birthdate', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Job', verbose_name='Cargo'),
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1)),
                ('day', models.IntegerField()),
                ('motive_perm', models.CharField(blank=True, max_length=500, null=True)),
                ('dscto', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Contracts')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['id'],
            },
        ),
    ]
