# Generated by Django 3.0.3 on 2020-07-25 02:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtsPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('total', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.Purchase')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('valor', models.IntegerField(default=0, verbose_name='Valor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frm.TypeExpense', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetDebtsPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('valor', models.IntegerField(default=0)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frm.DebtsPay')),
            ],
            options={
                'verbose_name': 'Det. Cuenta por pagar',
                'verbose_name_plural': 'Det. Cuentas por pagar',
                'ordering': ['-id'],
            },
        ),
    ]
