# Generated by Django 3.0.3 on 2020-07-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20200623_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='DESKTOP-MM4QS1D'),
        ),
        migrations.AlterField(
            model_name='company',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=9, verbose_name='Iva%'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='hostname',
            field=models.TextField(blank=True, default='DESKTOP-MM4QS1D', null=True),
        ),
    ]
