# Generated by Django 3.0.8 on 2020-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20200724_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=9, verbose_name='Iva%'),
        ),
    ]
